dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/tiledmap/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.tiledmap setup.py nosetests --ckan --with-pylons=ckanext/tiledmap/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.tiledmap --rednose

after_success: coveralls
